server:
  port: 8007
spring:
  rabbitmq:
    host: 192.168.164.128
    port: 5672
    username: laosun
    password: 123123
    virtual-host: lagou
    queue: order_queue
  redis:
    host: 192.168.164.128
    port: 6379
  application:
    name: edu-order-boot
  shardingsphere:
    datasource:
      names: ds0   #\u914D\u7F6E\u5E93\u7684\u540D\u5B57\uFF0C\u968F\u610F\uFF0C\u597D\u50CF\u8FD9\u91CC\u4E0D\u80FD\u6307\u5411\u591A\u4E2A\uFF08\u4E14\u5FC5\u987B\u6307\u5B9A\u4E00\u4E2A\u6570\u636E\u5E93\uFF09
      #\u53EF\u80FD\u662F\u6709\u539F\u56E0\u7684\uFF0C\u53EF\u4EE5\u767E\u5EA6\u67E5\u770B
      #\u6240\u4EE5\u5728\u67D0\u4E9B\u65F6\u5019\uFF0Cyml\u548Cyaml\u4E0Eproperties\u4E0D\u4E00\u6837
      #\u53EA\u662F\u5927\u81F4\u76F8\u540C\uFF08\u770B\u4E0B\u9762\u7684\u914D\u7F6E\u5C31\u77E5\u9053\uFF0C\u6709\u4E9B\u662F\u4E0D\u540C\u7684\uFF0C\u76F8\u5F53\u4E8E\u53BB\u6389_\uFF0C\u7136\u540E\u5BF9\u5E94\u540E\u9762\u7684\u5B57\u6BCD\u5927\u5199\uFF09
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.164.128:3306/edu_order?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        username: root
        password: QiDian@666
    sharding:
      tables:
        user_course_order:   # \u6307\u5B9Auser_course_order\u8868\u7684\u6570\u636E\u5206\u5E03\u60C5\u51B5\uFF0C\u914D\u7F6E\u6570\u636E\u8282\u70B9
          actualDataNodes: ds0.user_course_order_$->{0..2}
          tableStrategy:
            inline:   # \u6307\u5B9Auser_course_order\u8868\u7684\u5206\u7247\u7B56\u7565\uFF0C\u5206\u7247\u7B56\u7565\u5305\u62EC\u5206\u7247\u952E\u548C\u5206\u7247\u7B97\u6CD5
              shardingColumn: id
              algorithmExpression: user_course_order_$->{id % 3}
          keyGenerator:   # \u6307\u5B9Auser_course_order\u8868\u7684\u4E3B\u952E\u751F\u6210\u7B56\u7565\u4E3ASNOWFLAKE
            type: SNOWFLAKE  #\u4E3B\u952E\u751F\u6210\u7B56\u7565\u4E3ASNOWFLAKE
            column: id  #\u6307\u5B9A\u4E3B\u952E
  props:
    sql:
      show: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
ali:
  sms:
    signName: \u5927\u4F6C\u5B59
    templateCode: SMS_177536068
    assessKeyId: LTAI4FwKDkeZ6StZvRxg5RDf
    assessKeySecret: 09IMDRUia2uIC7HMXpSmM5CiXuUgvf